version: "3.9"

services:
  web:
    build: ./project
    command: python -m uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 5003
    volumes:
      - app-volume:/usr/src/app
    ports:
      - 5003:5003
    environment:
     - DATABASE_URL=postgres://postgres:postgres@web-db:5432/web_dev
     - DATABASE_TEST_URL=postgres://postgres:postgres@web-db:5432/web_test

  web-db:
    build: ./project/db
    expose:
     - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  app-volume: